server:
  port: 8888

spring:
  application:
    name: config-service
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: ${GITHUB_URL}
          default-label: master
          search-paths: '{application}'
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}